n1 = int(input('Informe um número: '))
print('Número escolhido {}'.format(n1))
print('O dobro de {} é igual a {}'.format(n1, n1*2))
print('O triplo de {} é igual a {}'.format(n1, n1*3))
print('A raiz quadrada de {} é igual a {}'.format(n1, n1**(1/2)))
