import time
print('\33[1;30m-=-\33[m'*15)
print('\33[1;31m- TABUADA -\33[m'.center(52))
print('\33[1;30m-=-\33[m'*15)
num = int(input('Digite o valor desejado para tabuada: '))
print('\33[1;32mCALCULANDO, AGUARDE...\33[m')
time.sleep(2)
print('{} X 1 = {}'.format(num, num * 1))
print('{} X 2 = {}'.format(num, num * 2))
print('{} X 3 = {}'.format(num, num * 3))
print('{} X 4 = {}'.format(num, num * 4))
print('{} X 5 = {}'.format(num, num * 5))
print('{} X 6 = {}'.format(num, num * 6))
print('{} X 7 = {}'.format(num, num * 7))
print('{} X 8 = {}'.format(num, num * 8))
print('{} X 9 = {}'.format(num, num * 9))
print('{} X 10 = {}'.format(num, num * 10))
