import math
angulo = float(input('Informe o ângulo: '))
seno = math.sin(math.radians(angulo))
cosseno = math.cos(math.radians(angulo))
tangente = math.tan(math.radians(angulo))
print('='*30)
print('Seno de {} vale: {:.2f}'.format(angulo, seno))
print('Cosseno de {} vale: {:.2f}'.format(angulo, cosseno))
print('Tangente de {} vale: {:.2f}'.format(angulo, tangente))
print('='*30)